* Taxation is theft, wile a government with a monopoly on force is necessary for the functioning of society, and the reconciliation of these facts.
** All state mandates are coercive. 
If I refuse to comply with some mandate of the state, say a minor one, I may first be given a warning or a citation. Later, if I continue to refuse to comply, I may be fined. If I refuse to pay the fine, I may be brought before a court. If that fails to convince me, I may be imprisoned. If I resist the effort to imprison me, I will be brought in by force. If I still continue to resist, I will be brought in under threat of deadly force, or killed.
** The state is nothing more than a collection of people.
** The state, as merely a group of individuals, has no right to deprive an individual.
** The proper task of the state is to manage the commons.
The state, as a representative of, or proxy, for a population, has better claim to administering the commons than any other individual, or any other group besides the totality of the population.
** The state does have the right to levy the costs of the commons on its users.
As the administrator of the commons, it is up to the state to protect the commons from damage, and to maintain it. The first of these tasks justifies the state limiting use of the commons, and levying punitive fines for misuse of the commons. The latter justifies the state charging for normal, but substantivly exculsionary usage of the commons, e.g. permanent occupation of a parcel of land to the exclusion of other potential land users.
