---
title: The Ethical and Economic Underpinnings of Georgism.
date: 2018-05-22
---
* Taxation is theft, while a government with a monopoly on force is necessary for the functioning of society, and the reconciliation of these facts.
** All state mandates are coercive.  
If I refuse to comply with some mandate of the state, even a minor one, I may first be given a warning or a citation.  Later, if I continue to refuse to comply, I may be fined.  If I refuse to pay the fine, I may be brought before a court.  If that fails to convince me, I may be imprisoned.  If I resist the effort to imprison me, I will be brought in by force.  If I still continue to resist, I will be brought in under threat of deadly force, or killed.  Even the most benign seeming of state mandates carry an implicit threat. Since all state mandates are coercive, they should be considered unethical until they are positively shown to be justified.
** The state is nothing more than a collection of people.
Groups are fuzzy edged abstractions that have no concrete existence except as a collection of individuals.  Groups supervene on individuals: a group is composed of individuals and you can not get a change in the properties of a group without some change in either which individuals compose the group or some change in the properties of those individuals.  Groups are useful abstractions, they compress large amounts of information about a multitude of individuals into a sparse set of common features; but not all concepts which are suitably applied to individuals are equally applicable to groups.
** The state, as merely a group of individuals, has no right to deprive an individual.
As groups are not moral entites, they do not have rights, which is a compressed shorthand for the fact that groups cannot be harmed, cannot suffer.  Groups are not entities worthy of moral consideration. Hence moral consideration for the well being of an individual must always take precedence over consideration of a group.  This is not the same as saying that any arbitrary individual's rights take precedence over the rights of a number of other individuals, but rather that groups 'qua' groups do not have rights above and beyond the rights of the individuals that compose that group.  

Groups therefore, should not impose upon individuals unless an argument can be made that this imposition is in fact in the defence of some individual's or some collection of individuals' rights.  

The state, like any other group, does not exist as an independent entity. "The State" is merely a shorthand name we give to the actions of individuals when their actions collected with others we deem state actions. In general, whether an action is a state action can only be determined by observing whether individuals typically regard it as a state action.
** The proper task of the state is to manage the commons.
The state, as a representative of, or proxy, for a population, has better claim to administering the commons than any other individual, or any other group besides the totality of the population.
** The state does have the right to levy the costs of the commons on its users.
As the administrator of the commons, it is up to the state to protect the commons from damage, and to maintain it.  The first of these tasks justifies the state limiting use of the commons, and levying punitive fines for misuse of the commons.  The latter justifies the state charging for normal, but substantivly exculsionary usage of the commons, e.g.  permanent occupation of a parcel of land to the exclusion of other potential land users.
** What you tax, you will get less of; what you subsidize you will get more of.  Economic reasons for LVT
Tax land usage and you'll get less land usage, but as the supply of land is fixed, you'll then necessarily get reduced land prices.
Tax production, the creation of the things that people want for the sake of their quality of life, and you'll get less wealth.
Tax negative externalities and you'll get fewer negative externalities.
TODO: find and link that paper purporting to prove that Georgist land value taxes are optimal in the sense of efficient resource allocation.
** What's mine is mine and what's yours is yours.  Principled reasons for LVT
Property rights do not exist in the world as anything substantial.  They are a fuzzy construct of individual agents interacting.  But they are a useful construct to be sure.  They may even qualify as universal in the sense found TODO:  provide explanation of the distinction between universal and necessary properties.
Once a conception of property rights is in place, it is easy to ground the exchange of property.  Property is the sole purview of an individual, and can therefore be done with by the individual as they please.  If an property holder wishes to transfer their property to another, they may do so.  In particular, they may do so as part of an agreement, contract of exchange with another potential property holder.
What is not solved by coming to a conception of property, is how property comes to be in the first place.  The transformation and exchange of property is simple, bu we need to find out how we can construct property in the first place.  A first candidate (and the only candidate I so far have come to accept) is in the Lockean enlightenment tradition: self-ownership.  If any one is to have claim of ownership over a person, symmetry alone should indicate that it is that very person.
