---
title: Univerals verus Necessities
date: 2018-05-22
---

Something is necessary if it could not be any other way.  Something is universal if we should (strongly) expect it to be the case, even without particular knowledge.
* Eyes are universals:
Eyes are not a necessary feature of life.  It is perfectly possible for a being to be alive and not have eyes, nor have eye-holding ancestors anywhere in its evolutionary tree.  But neither are eyes a mere happenstance accident of life on earth.  Eyes are an evolved (and evolvable) solution to an engineering problem likely to be faced by many beings in many worlds: how to navigate in the world.  It is advantageous for a being to be able to gather information about its surroundings remotely: if you have to touch the crocodile to figure out that it's a predator, it's already too late.  It is further advantageous if this information is directional: it's good to know which direction to go to run away from the crocodile.  Light is a conveniently available as a long range, directional source of information.  So long as it's not too difficult for evolutionary mechanisms to take advantage of, we should expect many evolved entites to use light collect information about their surroundings.  And indeed we do.  Not only do many animals on earth use light for information, but this information gathering ability has evolved dozens of times independently [CITE].  

Eyes are a univeral, but not necessary, solution to a universal problem.  
*  Prohibition on Murder:
Moral codes have something to do with the well-being of conscious entities.  It seems a reasonable hypothesis that, depending on exact the definitions in play and modulo scare-quotes, being murdered is bad for the well-being of a conscious entity.  This does not depend on any particular features of the conscious entity, other than that it be the sort of entity likely to exist, namely, that it be the sort of entity which could conceivably have evolved. Some restricted variant of self-preservation is a universal feature of evolved entities.  This allows us to say that it is true (!) that murder is bad, because it is a univeral feature of morally relevant entities that murder is harmful.
